const path = { type: "string", description: "File path, relative to the selected project or absolute. ~/ is supported. The project is not a sandbox." };
const hash = { type: ["string", "null"], description: "SHA-256 from read. For write, null means create only and never overwrite an existing file. For edit, null skips the read-version guard; exact matching still applies." };
export const fileTools = [
  { type: "function", name: "ls", strict: true,
    description: "List one directory, without recursion. Returns alphabetically sorted names, including dotfiles, with / after directories. Defaults to the selected project directory and 500 entries; output is bounded to 50 KiB. Use this for directory discovery instead of recursive find. Increase limit for more entries or list a specific subdirectory. Symlinked directories are marked but never traversed recursively. Control characters in names are JSON-escaped.",
    parameters: { type: "object", properties: { path: { type: ["string", "null"], description: "Directory path, relative to the selected project or absolute. ~/ is supported. Null means the project directory. This is not a sandbox." }, limit: { type: ["integer", "null"], description: "Maximum entries, a positive integer. Null means 500. Output remains bounded to 50 KiB." } }, required: ["path", "limit"], additionalProperties: false } },
  { type: "function", name: "read", strict: true,
    description: "Read a regular UTF-8 text file (up to 16 MiB). Returns SHA-256 of the original bytes and up to 2000 complete lines / 64 KiB. Line endings are shown as LF, with the UTF-8 BOM omitted. Follow next_offset until null to read all content. Binary files and oversized individual lines are rejected explicitly; use Bash for specialized inspection.",
    parameters: { type: "object", properties: { path, offset: { type: ["integer", "null"], description: "1-based starting line; null means 1." }, limit: { type: ["integer", "null"], description: "Maximum lines, 1–2000; null means 2000." } }, required: ["path", "offset", "limit"], additionalProperties: false } },
  { type: "function", name: "edit", strict: true,
    description: "Atomically edit one UTF-8 file using exact text replacements. Each nonempty oldText must match exactly once in the ORIGINAL file. Replacements must not overlap, including nested matches. All replacements succeed together or none are applied. Use LF in oldText/newText; uniform CRLF and BOM are preserved. Mixed line endings are rejected. Prefer supplying the SHA-256 from read to reject stale edits. No fuzzy matching. Read again after a mismatch; do not blindly retry.",
    parameters: { type: "object", properties: { path, expected_sha256: hash, edits: { type: "array", minItems: 1, maxItems: 100, items: { type: "object", properties: { oldText: { type: "string" }, newText: { type: "string" } }, required: ["oldText", "newText"], additionalProperties: false } } }, required: ["path", "edits", "expected_sha256"], additionalProperties: false } },
  { type: "function", name: "write", strict: true,
    description: "Atomically create or replace a UTF-8 text file. Creates missing parent directories. To replace an existing file, first read it and supply its SHA-256; null only allows creating a new file. Writes content exactly as supplied. Arguments are limited to 1 MiB encoded JSON. Use edit for targeted changes. A cancelled or uncertain operation may have committed: inspect before retrying.",
    parameters: { type: "object", properties: { path, content: { type: "string" }, expected_sha256: hash }, required: ["path", "content", "expected_sha256"], additionalProperties: false } },
];
export const isFileTool = (name: string) => name === "ls" || name === "read" || name === "edit" || name === "write";
